spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    userName: sa
    password: password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace



